config/routes.rb
Rails.application.routes.draw do

  resources :users, :only => [:index, :show]
  resources :downloads, only: [:show]
  # resources :activities, only: [:toggle_sts]

  devise_for :users, controllers: { sessions: 'users/sessions' }, path_prefix: 'd', path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  root to: 'home#index'

  resources :acts do
    collection do
      match 'search' => 'acts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'acts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'acts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'acts#hidden', via: [:get, :post], as: :hidden
    end
  end

  resources :conts do
    collection do
      match 'search' => 'conts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'conts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'conts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'conts#hidden', via: [:get, :post], as: :hidden

      match 'show_web' => 'conts#show_web', via: [:get, :post], as: :show_web
    end
  end

  resources :webs do
    get :flag_data, on: :collection

    collection do
      match 'search' => 'webs#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'webs#generate_csv', via: [:get, :post], as: :generate_csv
      match 'followed' => 'webs#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'webs#hidden', via: [:get, :post], as: :hidden
      match 'followed_acts' => 'webs#followed_acts', via: [:get, :post], as: :followed_acts
      match 'hidden_acts' => 'webs#hidden_acts', via: [:get, :post], as: :hidden_acts

      match 'show_conts' => 'webs#show_conts', via: [:get, :post], as: :show_conts
    end
  end

  resources :act_activities do
    collection do
      match 'follow_all' => 'act_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'act_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'act_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'act_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'act_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :cont_activities do
    collection do
      match 'follow_all' => 'cont_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'cont_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'cont_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'cont_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'cont_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :web_activities do
    collection do
      match 'follow_all' => 'web_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'web_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'web_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'web_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'web_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :queries do
    collection do
      match 'follow_all' => 'queries#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'queries#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'queries#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'queries#unhide_all', via: [:get, :post], as: :unhide_all
    end
  end

  resources :tallies, only: [:index] do
    collection do
      match 'follow_all' => 'tallies#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'tallies#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'tallies#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'tallies#unhide_all', via: [:get, :post], as: :unhide_all
      match 'generate_csv' => 'tallies#generate_csv', via: [:get, :post], as: :generate_csv
      match 'refresh_process' => 'tallies#refresh_process', via: [:get, :post], as: :refresh_process
    end
  end

  # resources :photos, only: [:new, :create, :index, :destroy]
  resources :photos, only: [:new, :create, :index, :destroy] do
    collection do
      match 'perform' => 'photos#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'photos#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :s3s, only: [:new, :create, :index, :destroy]
  resources :s3s, only: [:index, :destroy] do
    collection do
      match 'perform' => 's3s#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 's3s#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :exports, only: [:new, :create, :index, :destroy]
  resources :exports, only: [:index, :destroy] do
    collection do
      # match 'perform' => 'exports#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'exports#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  get 'admin/index'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  mount DelayedJobWeb => "/delayed_job"

  resources :terms, :links
end

app/views/webs/_download_webs.html.erb
<div id="download_webs">
  <% if params[:q].present? %>
    <% msg = 'Do you wish to Generate a CSV of these records?' %>
    <%= link_to generate_csv_webs_path(params), remote: false, data: { confirm: msg }, class: 'btn btn-primary btn-md' do %>
      <i class="fa fa-download" aria-hidden="true"></i> Generate CSV
    <% end %>
  <% end %>
</div>

app/views/webs/_form.html.erb
<%= form_with(model: web, remote: true) do |form| %>
  <% if web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web.errors.count, "error") %> prohibited this web from being saved:</h2>

      <ul>
      <% web.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webs/_web_details.html.erb
<!-- FIND OR CREATE activity -->
<% web_activity = current_user.web_activities.find_or_create_by(web_id: web.id) %>
<% web_export = Export.find_by(id: web_activity.export_id) %>

<!-- WEBS SECTION STARTS -->
<div class="row outer-list-row">
  <div class="col-md-3 association-parent">

    <table class="table details">
      <tr><td colspan="3"><%= link_to(icon('fas', 'home', web.url ), web.url, target: '_blank')%></td></tr>

      <% if web.fwd_url.present? %>
        <tr><td colspan="3"><%= link_to("F: #{web.fwd_url}", web.url, target: '_blank') %></td></tr>
      <% end %>

      <tr>
        <td colspan="2" style="width: 50%;">URL Status: <%= web.url_sts %> </td>
        <td style="width: 50%;">
          <% if web.fwd_url_id.present? %>
            <%= link_to("FWD URL Details", webs_path(fwd_web_id: web.fwd_url_id), target: '_blank', class: 'btn btn-primary btn-md') %>
          <% end %>
        </td>
      </tr>


      <tr>
        <td style="width: 30%;"><%= icon('fas', 'star', web.cop) %></td>
        <!-- WEB: TOGGLE STS PARTIAL - STARTS -->
        <td style="width: 30%;"><%= render 'web_activities/toggle_fav', web_activity: web_activity %></td>
        <td style="width: 30%;"><%= render 'web_activities/toggle_hide', web_activity: web_activity %></td>
      </tr>

      <tr><td colspan="3"><%= icon('fas', 'car', get_brands(web)&.join(', ')) %></td></tr>
      <tr><td colspan="3"><%= icon('fab', 'firstdraft', "#{web&.tmp_date&.strftime('%x')} #{web.temp_sts} #{web.temp_name}" )%></td></tr>
      <tr><td colspan="3"><%= icon('fas', 'link', "#{web&.page_date&.strftime('%x')} #{web.page_sts}" )%></td></tr>

      <tr>
        <td colspan="3"><%= icon('fas', 'users', "#{web&.cs_date&.strftime('%x')} #{web.cs_sts}" )%>
          <% cont_count = web.conts&.count %>

          <% if cont_count > 0 %>
            <%= link_to "Staff (#{cont_count})", show_conts_webs_path(web_id: web.id), onclick: "toggleConts(#{web.id})", remote: true, class: 'btn btn-primary btn-sm' %>
          <% end %>
        </td>
      </tr>

      <tr>
        <td colspan="3"><%= icon('fas', 'calendar-alt', "#{web&.created_at&.strftime('%x')} Created")%>
          <% if web.web_changed.present? %>
          | <%= web&.web_changed&.strftime('%x')%>: Updated
          <% end %>
        </td>
      </tr>

      <tr><td colspan="3"><%= icon('fas', 'download', "#{web_export&.export_date&.strftime('%x')} #{web_export&.file_name}" )%></td></tr>
    </table>
  </div>


  <!-- ACTS SECTION BEGINS -->
  <div class="col-md-9 outer-list-col">
    <% web.acts.each do |act| %>
    <!-- FIND OR CREATE web_activity -->
      <div class="row association-row">
        <%= render 'acts/act_details', act: act %>
      </div>
    <% end %>
  </div>

</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'webs/show_web_conts', web: web %>
  </div>
</div>

app/views/webs/_web_details_wrap.html.erb
<%= render 'webs/web_details', web: web %>

<div class='row contWrap' style="display:none" id="<%= web.id %>">
  <% if web.conts.any? %>
    <%= render 'conts/conts_list', conts: web.conts %>
  <% end %>
</div>

app/views/webs/_web_list.html.erb
<% web_activity = current_user.web_activities.find_or_create_by(web_id: web.id) %>
<% web_export = Export.find_by(id: web_activity.export_id) %>

<!-- WEBS SECTION STARTS -->
<div style="border-top: 1px solid gray; margin: 0; padding: 0;" class="col-md-12"></div>

<table class="table details">
  <tr>
    <td class='w25'><%= link_to(icon('fas', 'home', web.url ), web.url, target: '_blank')%></td>
    <td class='w10'><%= web.cop ? icon('fas', 'star', 'CoPilot') : icon('fas', 'star', 'Non-CoPilot') %> </td>

    <% brands = get_brands(web)&.join(', ') %>
    <% brands.present? ? brand_var = brands : brand_var = 'Non-Franchise'%>
    <td class='w15'><%= icon('fas', 'car', brand_var ) %></td>

    <td class='w10'><%= icon('fas', 'calendar-alt', web.created_at.strftime('%x') )%></td>

    <td class='w20'>
      <%= icon('fab', 'firstdraft', "#{web&.tmp_date&.strftime('%x')} #{web.temp_sts} #{web.temp_name}" ) if web.tmp_date.present? %>
    </td>

    <td class='w10'><%= render 'web_activities/toggle_fav', web_activity: web_activity %></td>
    <td class='w10'><%= render 'web_activities/toggle_hide', web_activity: web_activity %></td>
  </tr>

  <tr>
  <td class='w25'><%= link_to("F: #{web.fwd_url}", web.fwd_url, target: '_blank') if web.fwd_url.present? %></td>
  <td class='w10'><%= "𝚫 #{web&.web_changed&.strftime('%x')}" if web.web_changed.present? %></td>
  <td class='w15'><%= icon('fas', 'ban', web&.wx_date&.strftime('%x')) if web.wx_date.present? %></td>

  <td class='w10'><%= icon('fas', 'link', "#{web&.page_date&.strftime('%x')} #{web.page_sts}" ) if web.page_date.present? %></td>

  <td class='w20'>
    <% if web.cs_date.present? %>
      <%= icon('fas', 'users', "#{web&.cs_date&.strftime('%x')} #{web.cs_sts}" )%>
      <% cont_count = web.conts&.count %>

      <% if cont_count > 0 %>
        <%= link_to "Staff (#{cont_count})", show_conts_webs_path(web_id: web.id), onclick: "toggleConts(#{web.id})", remote: true, class: 'btn btn-primary btn-sm' %>
      <% end %>
    <% end %>
  </td>

  <td class='w20' colspan='2'><%= icon('fas', 'download', web_export&.file_name ) if web_export.present? %></td>
</tr>

</table>


<div class="row">
  <div class="col-md-12">
    <%= render 'webs/show_web_conts', web: web %>
  </div>
</div>

app/views/webs/_web_modal.html.erb
<!-- MODAL BUTTONS -->
<!-- <button type="button" class="btn btn-xs" style="color: white; background: black;" data-toggle="modal" data-target="#viewWebModal">View Web </button> -->
<!-- <td class="cont-acts w10"><a href="#" class="btn btn-sm" data-toggle="modal" data-target="#viewWebModal">Details</a></td> -->

<!-- Modal -->
  <div class="modal fade" id="viewWebModal" role="dialog">
    <!-- <div class="row modal-dialog"> -->
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header"><h4>Account Details</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title text-center">Close</h4>
        </div>

        <!-- Modal body-->
          <div class="modal-body" style="background: black;">
            <%#= render 'webs/web_details', web: web %>
            <%#= render 'conts/show_cont_web', cont: cont %>
        </div>

      </div>

    </div>
  </div>


<!-- this modal is not being used! -->

app/views/webs/_webs.html.erb
<%= render 'shared/webs_sidebar_btn' %>

<p id="notice"><%= notice %></p>

<div class="panel section-panel">
  <div class="row">
    <div class="col-md-3">
      <h5><%= icon('fas', 'external-link-alt', 'Websites') %> <span style="font-size: 14px;">(Results: <%= number_with_delimiter(@webs.count, :delimiter => ',') %> )</h5></span>
    </div>

    <div class="col-md-3">
      <%= render 'webs/download_webs', webs: @webs %>
    </div>

    <div class="col-md-4"></div>

    <div class="col-md-2">
      <button class="btn btn-danger btn-tip" onclick="websHeaderTipModal()"><%= icon('fas', 'exclamation-circle', 'Websites Tip') %></button>
    </div>

  </div>

  <div class="row header-tip-modals" id="websHeaderTipModalWrap">
    <div class="col-md-12">
      <h6 class=""> <span class="font-weight-bold">TIP</span>: The Websites Module primarily focuses on URLs, their status, and relation to their associated data, such as their Accounts and Contacts.  URL data is listed on left and associated Accounts listed on right. Click blue 'Staff' button in left URL Section to view Scraped Contacts; if they exist. Search Websites via <span style="font-size: 10px;"><%= icon('fas', 'search') %></span>  icon in top right corner.  It's important to note that each Website URL can have multiple Accounts and each Account can have multiple Website URLs.  Using 'Follow' and 'Hide' is designed to help determine if you have already viewed that same data in another section.</h6>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-3 text-center">
    <h5 class="section-header">Websites</h5>
  </div>

  <div class="col-md-9 text-center">
    <h5 class="section-header">Associated Accounts</h5>
  </div>
</div>

















<div class="panel outer-panel">

  <% @webs.each do |web| %>
    <% @web = web %>
    <%= render 'webs/web_details', web: @web %>
  <% end %>
</div>


<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-8 text-center">
    <%= will_paginate @webs %>
  </div>
</div>

app/views/webs/_webs_partial.html.erb
<%= render partial: 'shared/webs_sidebar_btn' %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <h5>Web Based View (Results: <%= @webs.count %>)</h5>
  </div>
</div>

<% if params[:q].present? %>
  <div class="row">
    <%= link_to generate_csv_webs_path(params), class: 'btn btn-primary btn-xs' do %>
      <i class="fa fa-download" aria-hidden="true"></i> Download CSV
    <% end %>
  </div>
<% end %>



<div class="panel outer-panel">
  <% @webs.each do |web| %>
    <!-- FIND OR CREATE web_activity -->
    <% web_activity = current_user.activities.find_or_create_by(mod_name: 'Web', mod_id: web.id) %>
    <% web_export = Export.find_by(id: web_activity.export_id) %>

    <!-- WEBS SECTION STARTS -->
    <div class="row outer-list-row">
      <div class="col-md-3 association-parent">
        <p><%= link_to(icon('fas', 'home', web.url ), web.url, target: '_blank')%></p>
        <p><%= icon('fas', 'car', get_brands(web)&.join(', ')) %></p>
        <p><%= icon('fas', 'star', web.cop) %></p>
        <p><%= icon('fab', 'firstdraft', "#{web&.tmp_date&.strftime('%x')} #{web.temp_sts} #{web.temp_name}" )%></p>
        <p><%= icon('fas', 'link', "#{web&.page_date&.strftime('%x')} #{web.page_sts}" )%></p>

        <p><%= icon('fas', 'users', "#{web&.cs_date&.strftime('%x')} #{web.cs_sts}" )%>
          <% cont_count = web.conts&.count %>
          <% if cont_count > 0 %>
            | <a href="#" onclick="toggleConts(<%= web.id %>);return false;">Staff (<%= cont_count %>)</a>
          <% end %>
        </p>

        <p><%= icon('fas', 'calendar-alt', "#{web&.created_at&.strftime('%x')} Created")%>
          <% if web.web_changed.present? %>
          | <%= web&.web_changed&.strftime('%x')%>: Updated
          <% end %>
        </p>

        <p><%= icon('fas', 'download', "#{web_export&.export_date&.strftime('%x')} #{web_export&.file_name}" )%></p>

        <!-- WEB: TOGGLE STS PARTIAL - STARTS -->
        <%= render partial: "activities/toggle_sts_partial", locals: { activity: web_activity } %>
      </div>


      <!-- ACTS SECTION BEGINS -->
      <div class="col-md-9 outer-list-col">
        <% web.acts.each do |act| %>
        <!-- FIND OR CREATE web_activity -->
        <% act_activity = current_user.activities.find_or_create_by(mod_name: 'Act', mod_id: act.id) %>
        <% act_export = Export.find_by(id: act_activity.export_id) %>

          <div class="row association-row">

            <div class="col-md-5">
              <p><%= icon('fas', 'building', act.act_name) %></p>
              <p><%= icon('fas', 'address-card', act.full_address) %></p>
              <p><%= icon('fas', 'phone', act.phone) %></p>

              <!-- ACT: TOGGLE STS PARTIAL - STARTS -->
              <%= render partial: "activities/toggle_sts_partial", locals: { activity: act_activity } %>
            </div>

            <div class="col-md-4">
              <p><%= icon('fab', 'google', "Places: #{act.gp_sts}")%>: <%= act.gp_date&.strftime('%x')%></p>
              <p><%= icon('fab', 'google', "# #{act.gp_id}") %></p>
              <p><%= icon('fas', 'map-marker-alt', "#{act.lat}, #{act.lon}") %></p>
              <p><%= icon('fas', 'download', "#{act_export&.export_date&.strftime('%x')} #{act_export&.file_name}" )%></p>
            </div>

            <div class="col-md-3">
              <p><%= icon('fas', 'calendar-alt', "Name Updated: #{act.act_changed&.strftime('%x')}" ) %></p>
              <p><%= icon('fas', 'calendar-alt', "Address Updated: #{act.adr_changed&.strftime('%x')}" ) %></p>
              <p><%= icon('fas', 'calendar-alt', "Created: #{act.created_at.strftime('%x')}" ) %></p>
            </div>

          </div>
        <% end %>
      </div>
    </div>


    <div class='row contWrap' style="display:none" id="<%= web.id %>">
      <% if web.conts.any? %>
        <% @conts = web.conts %>
        <%= render 'conts/conts_list_partial', conts: @conts %>
      <% end %>
    </div>


  <% end %>

  <br>
  <%= will_paginate @webs if @webs.present? %>
  <br>
  <br>
</div>

app/views/webs/edit.html.erb
<h1>Editing Web</h1>

<%= render 'form', web: @web %>

<%= link_to 'Show', @web %> |
<%= link_to 'Back', webs_path %>

app/views/webs/index.html.erb
<%= render 'webs', webs: @webs %>

app/views/webs/index.js.erb
$("#yield-content").html("<%= j (render 'webs', webs: @webs) %>");

app/views/webs/new.html.erb
<h1>New Web</h1>

<%= render 'form', web: @web %>

<%= link_to 'Back', webs_path %>

app/views/webs/save_form.html.erb
<% if web&.present? %>

<%= form_with(model: web, remote: true) do |form| %>
  <% if web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web.errors.count, "error") %> prohibited this web from being saved:</h2>

      <ul>
      <% web.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<% end %>

app/views/webs/show.html.erb
<p id="notice"><%= notice %></p>