config/routes.rb
Rails.application.routes.draw do

  resources :users, :only => [:index, :show]
  resources :downloads, only: [:show]
  # resources :activities, only: [:toggle_sts]

  devise_for :users, controllers: { sessions: 'users/sessions' }, path_prefix: 'd', path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  root to: 'home#index'

  resources :acts do
    collection do
      match 'search' => 'acts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'acts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'acts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'acts#hidden', via: [:get, :post], as: :hidden
    end
  end

  resources :conts do
    collection do
      match 'search' => 'conts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'conts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'conts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'conts#hidden', via: [:get, :post], as: :hidden

      match 'show_web' => 'conts#show_web', via: [:get, :post], as: :show_web
    end
  end

  resources :webs do
    get :flag_data, on: :collection

    collection do
      match 'search' => 'webs#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'webs#generate_csv', via: [:get, :post], as: :generate_csv
      match 'followed' => 'webs#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'webs#hidden', via: [:get, :post], as: :hidden
      match 'followed_acts' => 'webs#followed_acts', via: [:get, :post], as: :followed_acts
      match 'hidden_acts' => 'webs#hidden_acts', via: [:get, :post], as: :hidden_acts

      match 'show_conts' => 'webs#show_conts', via: [:get, :post], as: :show_conts
    end
  end

  resources :act_activities do
    collection do
      match 'follow_all' => 'act_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'act_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'act_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'act_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'act_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :cont_activities do
    collection do
      match 'follow_all' => 'cont_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'cont_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'cont_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'cont_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'cont_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :web_activities do
    collection do
      match 'follow_all' => 'web_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'web_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'web_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'web_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'web_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :queries do
    collection do
      match 'follow_all' => 'queries#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'queries#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'queries#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'queries#unhide_all', via: [:get, :post], as: :unhide_all
    end
  end

  resources :tallies, only: [:index] do
    collection do
      match 'follow_all' => 'tallies#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'tallies#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'tallies#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'tallies#unhide_all', via: [:get, :post], as: :unhide_all
      match 'generate_csv' => 'tallies#generate_csv', via: [:get, :post], as: :generate_csv
      match 'refresh_process' => 'tallies#refresh_process', via: [:get, :post], as: :refresh_process
    end
  end

  # resources :photos, only: [:new, :create, :index, :destroy]
  resources :photos, only: [:new, :create, :index, :destroy] do
    collection do
      match 'perform' => 'photos#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'photos#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :s3s, only: [:new, :create, :index, :destroy]
  resources :s3s, only: [:index, :destroy] do
    collection do
      match 'perform' => 's3s#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 's3s#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :exports, only: [:new, :create, :index, :destroy]
  resources :exports, only: [:index, :destroy] do
    collection do
      # match 'perform' => 'exports#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'exports#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  get 'admin/index'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  mount DelayedJobWeb => "/delayed_job"

  resources :terms, :links
end

app/views/shared/_acts_sidebar_btn.html.erb
<div class="row toggle-sidebar pull-left">
  <button type="button" id="acts-sidebar-collapse" class="btn navbar-btn">
    <h5><%= icon('fas', 'search', class: 'fa-pull-left') %></h5>
  </button>
</div>

app/views/shared/_conts_sidebar_btn.html.erb
<div class="row toggle-sidebar pull-left">
  <button type="button" id="conts-sidebar-collapse" class="btn navbar-btn">
    <h5><%= icon('fas', 'search', class: 'fa-pull-left') %></h5>
  </button>
</div>

app/views/shared/_errors.html.erb
<% if object && object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

  <div class='flash_wrap flash_notice'>
    <%= flash[:notice] %>
  </div>

<% elsif flash.now[:alert] %>

  <div class='flash_wrap flash_alert'>
    <%= flash.now[:alert] %>
  </div>

<% elsif flash[:alert] %>

  <div class='flash_wrap flash_alert'>
    <%= flash[:alert] %>
  </div>

<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer style="background: #252830; font-size: 16px;">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <span class="copyright">Copyright © Sage DataForce 2018</span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_mobile_alert.html.erb
<div class="view-in-mobile view-types text-center">
  <h5>Mobile Device Notice</h5>
  <p>Mobile Version Pending Release</p>
  <p>Please use laptop or desktop</p>

</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

  <div class="container-fluid">

    <div class="navbar-header">

      <button type="button" class="view-in-mobile hamburger navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <%= icon('fas', 'bars') %>
      </button>

      <%= link_to(icon('fas', 'database', 'Sage DataForce'), root_path, class: "navbar-brand")%>

    </div>

    <div class="collapse navbar-collapse collapse-in-mobile" id="myNavbar">

      <ul class="nav navbar-nav">

        <% if basic_and_up %>
          <li><%= link_to(icon('fas', 'building', 'Accounts'), acts_path, class: "nav-link")%></li>
          <li><%= link_to(icon('fas', 'users', 'Contacts'), conts_path, class: "nav-link")%></li>
          <li><%= link_to(icon('fas', 'external-link-alt', 'Websites'), webs_path, class: "nav-link")%></li>
          <li><%= link_to(icon('fas', 'tachometer-alt', 'Dashboard'), tallies_path, class: "nav-link")%></li>
        <% end %>

        <% if current_user.present? %>
          <li><%= link_to(icon('fas', 'user-circle', current_user.first_name.capitalize), user_path(current_user), class: "nav-link")%></li>
        <% else %>
          <li class="nav-item"><%= link_to "Register", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>

        <% if admin_only %>
          <li class="nav-item"><%= link_to 'Admin', admin_index_path, class: "nav-link"  %></li>
          <li class="nav-item"><%= link_to 'Queue', delayed_job_web_path, class: "nav-link"  %></li>
        <% end %>
      </ul>

    </div>

  </div>

</nav>

app/views/shared/_sidebar.html.erb
<% if @wq.present? %>
  <%= render 'shared/webs_sidebar' %>
<% elsif @cq.present? %>
  <%= render 'shared/conts_sidebar' %>
<% elsif @aq.present? %>
  <%= render 'shared/acts_sidebar' %>
<% end%>

app/views/shared/_sidebar_btn.html.erb
<div class="row toggle-sidebar pull-left">
  <button type="button" id="sidebarCollapse" class="btn navbar-btn">
    <h5><%= icon('fas', 'search', class: 'fa-pull-left') %></h5>
  </button>
</div>

app/views/shared/_webs_sidebar_btn.html.erb
<div class="row toggle-sidebar pull-left">
  <button type="button" id="webs-sidebar-collapse" class="btn navbar-btn">
    <h5><%= icon('fas', 'search', class: 'fa-pull-left') %></h5>
  </button>
</div>