config/routes.rb
Rails.application.routes.draw do

  resources :users, :only => [:index, :show]
  resources :downloads, only: [:show]
  # resources :activities, only: [:toggle_sts]

  devise_for :users, controllers: { sessions: 'users/sessions' }, path_prefix: 'd', path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  root to: 'home#index'

  resources :acts do
    collection do
      match 'search' => 'acts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'acts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'acts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'acts#hidden', via: [:get, :post], as: :hidden
    end
  end

  resources :conts do
    collection do
      match 'search' => 'conts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'conts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'conts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'conts#hidden', via: [:get, :post], as: :hidden

      match 'show_web' => 'conts#show_web', via: [:get, :post], as: :show_web
    end
  end

  resources :webs do
    get :flag_data, on: :collection

    collection do
      match 'search' => 'webs#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'webs#generate_csv', via: [:get, :post], as: :generate_csv
      match 'followed' => 'webs#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'webs#hidden', via: [:get, :post], as: :hidden
      match 'followed_acts' => 'webs#followed_acts', via: [:get, :post], as: :followed_acts
      match 'hidden_acts' => 'webs#hidden_acts', via: [:get, :post], as: :hidden_acts

      match 'show_conts' => 'webs#show_conts', via: [:get, :post], as: :show_conts
    end
  end

  resources :act_activities do
    collection do
      match 'follow_all' => 'act_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'act_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'act_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'act_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'act_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :cont_activities do
    collection do
      match 'follow_all' => 'cont_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'cont_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'cont_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'cont_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'cont_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :web_activities do
    collection do
      match 'follow_all' => 'web_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'web_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'web_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'web_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'web_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :queries do
    collection do
      match 'follow_all' => 'queries#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'queries#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'queries#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'queries#unhide_all', via: [:get, :post], as: :unhide_all
    end
  end

  resources :tallies, only: [:index] do
    collection do
      match 'follow_all' => 'tallies#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'tallies#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'tallies#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'tallies#unhide_all', via: [:get, :post], as: :unhide_all
      match 'generate_csv' => 'tallies#generate_csv', via: [:get, :post], as: :generate_csv
      match 'refresh_process' => 'tallies#refresh_process', via: [:get, :post], as: :refresh_process
    end
  end

  # resources :photos, only: [:new, :create, :index, :destroy]
  resources :photos, only: [:new, :create, :index, :destroy] do
    collection do
      match 'perform' => 'photos#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'photos#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :s3s, only: [:new, :create, :index, :destroy]
  resources :s3s, only: [:index, :destroy] do
    collection do
      match 'perform' => 's3s#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 's3s#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :exports, only: [:new, :create, :index, :destroy]
  resources :exports, only: [:index, :destroy] do
    collection do
      # match 'perform' => 'exports#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'exports#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  get 'admin/index'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  mount DelayedJobWeb => "/delayed_job"

  resources :terms, :links
end

app/controllers/conts_controller.rb
class ContsController < ApplicationController
  before_action :set_cont, only: [:show, :edit, :update, :destroy]
  before_action :basic_and_up
  helper_method :sort_column, :sort_direction
  require 'will_paginate/array'

  def index

    if params[:bypass_cont_ids]&.any?
      @conts = Cont.where(id: [params[:bypass_cont_ids]]).order("updated_at DESC").paginate(page: params[:page], per_page: 20)
    elsif params[:grab_followed].present?
      cont_ids = current_user.cont_activities.followed.pluck(:cont_id)
      @conts = Cont.where(id: [cont_ids]).order("updated_at DESC").paginate(page: params[:page], per_page: 20)
    elsif params[:grab_hidden].present?
      cont_ids = current_user.cont_activities.hidden.pluck(:cont_id)
      @conts = Cont.where(id: [cont_ids]).order("updated_at DESC").paginate(page: params[:page], per_page: 20)
    else
      params.delete('q') if params['q'].present? && params['q'] == 'q'

      ## Splits 'cont_any' strings into array, if string and has ','
      if params[:q].present?
        conts_helper = Object.new.extend(ContsHelper)
        params[:q] = conts_helper.split_ransack_params(params[:q])
      end

      @cq = Cont.ransack(params[:q])
      @conts = @cq.result(distinct: true).includes(:acts, :web, :brands, :act_activities, :cont_activities, :web_activities).order("updated_at DESC").paginate(page: params[:page], per_page: 20)
    end

    @cq = Cont.ransack(params[:q]) if !@cq.present?
  end


  def show_web
    @cont = Cont.find(params[:cont_id])
    respond_to do |format|
      format.js { render :show_web, status: :ok, location: @cont }
    end
  end


  def followed
    params[:bypass_cont_ids] = helpers.get_followed_cont_ids(nil)
    redirect_to conts_path(params)
  end

  def hidden
    params[:bypass_cont_ids] = helpers.get_hidden_cont_ids(nil)
    redirect_to conts_path(params)
  end


  def generate_csv
    flash[:notice] = "Generating CSV: Available in Exports Section when completed."
    Cont.generate_csv_conts(params, current_user) if params[:q].present?
    redirect_to user_path(current_user)
  end


  def search
    if params[:q]['q_name_cont_any'].present?
      q_name = params[:q].delete('q_name_cont_any')
      ContCsvTool.new.save_cont_queries(q_name, params, current_user)
    end

    index
    render :index
  end


  def show
  end

  def new
    @cont = Cont.new
  end

  def edit
  end

  def create
    @cont = Cont.new(cont_params)
    respond_to do |format|
      if @cont.save
        format.html { redirect_to @cont, notice: 'Cont was successfully created.' }
        format.json { render :show, status: :created, location: @cont }
      else
        format.html { render :new }
        format.json { render json: @cont.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cont.update(cont_params)
        format.html { redirect_to @cont, notice: 'Cont was successfully updated.' }
        format.json { render :show, status: :ok, location: @cont }
      else
        format.html { render :edit }
        format.json { render json: @cont.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cont.destroy
    respond_to do |format|
      format.html { redirect_to conts_url, notice: 'Cont was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def sort_column
      Cont.column_names.include?(params[:sort]) ? params[:sort] : "full_name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_cont
      @cont = Cont.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cont_params
      # params.require(:cont).permit(:src, :sts, :act_id, :crma, :crmc, :first_name, :last_name, :email)

      params.require(:cont).permit(:id, :first_name, :last_name, :full_name, :job_title, :job_desc, :email, :phone, :cs_sts, :cs_date, :email_changed, :cont_changed, :job_changed, :cx_date, :web_id)
    end
end

app/helpers/conts_helper.rb
module ContsHelper

  ## Splits 'cont_any' strings into array, if string and has ','
  def split_ransack_params(params)
    # ACTS
    acts_act_name = params[:acts_act_name_cont_any]
    acts_city = params[:acts_city_cont_any]
    acts_state = params[:acts_state_cont_any]
    acts_zip = params[:acts_zip_cont_any]
    acts_phone = params[:acts_phone_cont_any]
    acts_lat = params[:acts_lat_cont_any]
    acts_lon = params[:acts_lon_cont_any]
    acts_gp_id = params[:acts_gp_id_cont_any]

    params[:acts_act_name_cont_any] = ransack_splitter(acts_act_name) if acts_act_name
    params[:acts_city_cont_any] = ransack_splitter(acts_city) if acts_city
    params[:acts_state_cont_any] = ransack_splitter(acts_state) if acts_state
    params[:acts_zip_cont_any] = ransack_splitter(acts_zip) if acts_zip
    params[:acts_phone_cont_any] = ransack_splitter(acts_phone) if acts_phone
    params[:acts_lat_cont_any] = ransack_splitter(acts_lat) if acts_lat
    params[:acts_lon_cont_any] = ransack_splitter(acts_lon) if acts_lon
    params[:acts_gp_id_cont_any] = ransack_splitter(acts_gp_id) if acts_gp_id


    # CONTS
    full_name = params[:full_name_cont_any]
    first_name = params[:first_name_cont_any]
    last_name = params[:last_name_cont_any]
    job_title = params[:job_title_cont_any]
    job_desc = params[:job_desc_cont_any]
    email = params[:email_cont_any]
    phone = params[:phone_cont_any]

    params[:full_name_cont_any] = ransack_splitter(full_name) if full_name
    params[:first_name_cont_any] = ransack_splitter(first_name) if first_name
    params[:last_name_cont_any] = ransack_splitter(last_name) if last_name
    params[:job_title_cont_any] = ransack_splitter(job_title) if job_title
    params[:job_desc_cont_any] = ransack_splitter(job_desc) if job_desc
    params[:email_cont_any] = ransack_splitter(email) if email
    params[:phone_cont_any] = ransack_splitter(phone) if phone

    # WEBS
    web_url = params[:web_url_cont_any]
    web_fwd_url = params[:web_fwd_url_cont_any]

    params[:web_url_cont_any] = ransack_splitter(web_url) if web_url
    params[:web_fwd_url_cont_any] = ransack_splitter(web_fwd_url) if web_fwd_url

    return params
  end


  def ransack_splitter(field)
    field = field.split(',').map{|part| part.strip} if field.is_a?(String)
    return field
  end

end

app/views/conts/_cont_detail.html.erb
<% cont_activity = current_user.cont_activities.find_or_create_by(cont_id: cont.id) %>
<% cont_export = Export.find_by(id: cont_activity.export_id) %>

<div class="row outer-list-row">

  <div class="col-md-6">
    <table class="table details">
    <tr>
      <td style="width: 60%;"><%= icon('fas', 'user', cont.full_name) %></td>

      <td style="width: 10%;"><%= render 'cont_activities/toggle_fav', cont_activity: cont_activity %></td>
      <td style="width: 10%;"><%= render 'cont_activities/toggle_hide', cont_activity: cont_activity %></td>
      <td style="width: 10%;">Created:</td>
      <td style="width: 10%;"><%= cont.created_at&.strftime('%x') %></td>
    </tr>

    <tr>
      <td colspan="3" style="width: 80%;"><%= icon('fas', 'briefcase', "#{cont.job_title} | #{cont.job_desc}") %> </td>
      <td style="width: 10%;">Verified:</td>
      <td style="width: 10%;"><%= cont.cs_date&.strftime('%x') %></td>
    </tr>


    <tr>
      <td colspan="3" style="width: 80%;">
        <% cont.phone.present? ? cont_phone = cont.phone : cont_phone = "no phone"%>
        <% cont.email.present? ? cont_email = cont.email : cont_email = "no email"%>

        <%= icon('fas', 'phone', cont_phone) %> |
        <%= icon('fas', 'at', cont_email) %>
      </td>
      <td style="width: 10%;">Email 𝚫:</td>
      <td style="width: 10%;"><%= cont.email_changed&.strftime('%x') %></td>
    </tr>

    <tr>
      <td colspan="3" style="width: 80%;"><%= link_to(icon('fas', 'home', cont.web.url ), cont.web.url, target: '_blank')%></td>
      <td style="width: 10%;">Job 𝚫:</td>
      <td style="width: 10%;"><%= cont.job_changed&.strftime('%x') %></td>
    </tr>

    <tr>
      <td colspan="2" style="width: 33%;"><%= icon('fas', 'download', "#{cont_export&.export_date&.strftime('%x')} #{cont_export&.file_name}" )%></td>
    </tr>
  </table>
  </div>

  <div class="col-md-6">
    <table class="table details">
    <% acts = cont.acts %>
    <% acts&.each do |act| %>

      <!-- FIND OR CREATE act_activity -->
      <% act_activity = current_user.act_activities.find_or_create_by(act_id: act.id) %>
      <% act_export = Export.find_by(id: act_activity.export_id) %>

      <tr class="cont-acts">
        <td class="cont-acts w70"><%= act.act_name %> | <%= act.full_address %> </td>

        <td>
          <%= link_to "Details", show_web_conts_path(cont_id: cont.id), onclick: "toggleWeb(#{cont.id})", remote: true, class: 'btn btn-primary btn-sm' %>
        </td>

        <!-- ACT: TOGGLE STS PARTIAL - STARTS -->
        <td class="cont-acts w10"><%= render 'act_activities/toggle_fav', act_activity: act_activity %></td>
        <td class="cont-acts w10"><%= render 'act_activities/toggle_hide', act_activity: act_activity %></td>
      </tr>
    <% end %>
  </table>
  </div>

</div>


<div class="row"">
  <div class="col-md-12">
    <%= render 'conts/show_cont_web', cont: cont %>
  </div>
</div>

app/views/conts/_conts.html.erb
<%= render 'shared/conts_sidebar_btn' %>

<p id="notice"><%= notice %></p>



<div class="panel section-panel">
  <div class="row">
    <div class="col-md-3">
      <h5><%= icon('fas', 'users', 'Contacts') %> <span style="font-size: 14px;">(Results: <%= number_with_delimiter(conts.count, :delimiter => ',') %> )</span></h5>
    </div>

    <div class="col-md-3">
      <%= render 'conts/download_conts', conts: conts %>
    </div>

    <div class="col-md-4"></div>

    <div class="col-md-2">
      <button class="btn btn-danger btn-tip" onclick="contsHeaderTipModal()"><%= icon('fas', 'exclamation-circle', 'Contacts Tip') %></button>
    </div>
  </div>

  <div class="row header-tip-modals" id="contsHeaderTipModalWrap">
    <div class="col-md-12">
      <h6 class=""> <span class="font-weight-bold">TIP</span>: The Contacts Module primarily focuses on Employees scraped from an Account's Website's staff page, and their relationship to their associated data, such as their Accounts and Websites.  Contact data is listed on the left and its associated Accounts are listed on the right. Click blue 'Details' button in right Account Section to view Website Details and all its Scraped Contacts. Search Contacts via <span style="font-size: 10px;"><%= icon('fas', 'search') %></span>  icon in top right corner.  It's important to note that a contact can be associated with multiple Accounts or multiple website URLs, due to each Website URL often having multiple Accounts and each Account often having multiple Website URLs.  Using 'Follow' and 'Hide' is designed to help determine if you have already viewed that same data in another section.</h6>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-6 text-center">
    <h5 class="section-header">Contacts</h5>
  </div>

  <div class="col-md-6 text-center">
    <h5 class="section-header">Associated Accounts</h5>
  </div>
</div>





<div class="row">
  <% conts&.each do |cont| %>
    <div class="col-md-12">
      <%= render 'conts/cont_detail', cont: cont %>
    </div>
  <% end %>
</div>



<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-8 text-center">
    <%= will_paginate conts %>
  </div>
</div>

app/views/conts/_conts_detail.html.erb
<%= render partial: 'shared/conts_sidebar_btn' %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <h5>Contacts (Results: <%= @conts.count %>)</h5>
  </div>
</div>


<% if params[:q].present? %>
  <div class="row">
    <%= link_to generate_csv_conts_path(params), class: 'btn btn-primary btn-xs' do %>
      <i class="fa fa-download" aria-hidden="true"></i> Download CSV
    <% end %>
  </div>
<% end %>



<div class="row">
  <% @conts&.each_with_index do |cont, index| %>
    <% if index.even? %>
    <!-- LEFT -->
      <div class="col-md-6">
        <div class="col-md-12">
          <%= render 'conts_detail_deep', cont: cont %>
        </div>
      </div>
    <% else %>
      <!-- RIGHT -->
      <div class="col-md-6">
        <div class="col-md-12">
          <%= render 'conts_detail_deep', cont: cont %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/conts/_conts_detail_deep.html.erb
<!-- <div class="panel outer-panel list-view"> -->
  <% @activity = current_user.activities.find_or_create_by(mod_name: 'Cont', mod_id: cont.id) %>
  <% cont_export = Export.find_by(id: @activity.export_id) %>

  <div class="row outer-list-row">

    <!-- <div class="row"> -->
      <table class="table details">
        <tr>
          <td style="width: 60%;"><%= icon('fas', 'user', cont.full_name) %></td>

          <td style="width: 10%;"><%= render 'activities/toggle_fav_wrap', locals: {activity: @activity} %></td>
          <td style="width: 10%;"><%= render 'activities/toggle_hide_wrap', locals: {activity: @activity} %></td>
          <td style="width: 10%;">Created:</td>
          <td style="width: 10%;"><%= cont.created_at&.strftime('%x') %></td>
        </tr>

        <tr>
          <td colspan="3" style="width: 80%;"><%= icon('fas', 'briefcase', "#{cont.job_title} | #{cont.job_desc}") %> </td>
          <td style="width: 10%;">Verified:</td>
          <td style="width: 10%;"><%= cont.cs_date&.strftime('%x') %></td>
        </tr>


        <tr>
          <td colspan="3" style="width: 80%;">
            <% cont.phone.present? ? cont_phone = cont.phone : cont_phone = "no phone"%>
            <% cont.email.present? ? cont_email = cont.email : cont_email = "no email"%>

            <%= icon('fas', 'phone', cont_phone) %> |
            <%= icon('fas', 'at', cont_email) %>
          </td>
          <td style="width: 10%;">Email 𝚫:</td>
          <td style="width: 10%;"><%= cont.email_changed&.strftime('%x') %></td>
        </tr>

        <tr>
          <td colspan="3" style="width: 80%;"><%= link_to(icon('fas', 'home', cont.web.url ), cont.web.url, target: '_blank')%></td>
          <td style="width: 10%;">Job 𝚫:</td>
          <td style="width: 10%;"><%= cont.job_changed&.strftime('%x') %></td>
        </tr>

        <tr>
          <td colspan="2" style="width: 33%;"><%= icon('fas', 'download', "#{cont_export&.export_date&.strftime('%x')} #{cont_export&.file_name}" )%></td>
        </tr>
      </table>
    <!-- </div> -->


    <% acts = cont.acts %>
    <% acts&.each do |act| %>

      <!-- FIND OR CREATE act_activity -->
      <% @activity = current_user.activities.find_or_create_by(mod_name: 'Act', mod_id: act.id) %>
      <% act_export = Export.find_by(id: @activity.export_id) %>
      <table class="table details">
        <tr class="cont-acts">
          <td class="cont-acts w80"><%= act.act_name %> | <%= act.full_address %> </td>
          <!-- ACT: TOGGLE STS PARTIAL - STARTS -->
          <td class="cont-acts w10"><%= render 'activities/toggle_fav_wrap', locals: {activity: @activity} %></td>
          <td class="cont-acts w10"><%= render 'activities/toggle_hide_wrap', locals: {activity: @activity} %></td>
        </tr>
      </table>
    <% end %>

  </div>
<!-- </div> -->

app/views/conts/_conts_detail_partial.html.erb
<%= render partial: 'shared/conts_sidebar_btn' %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <h5>Contacts (Results: <%= @conts.count %>)</h5>
  </div>
</div>


<% if params[:q].present? %>
  <div class="row">
    <%= link_to generate_csv_conts_path(params), class: 'btn btn-primary btn-xs' do %>
      <i class="fa fa-download" aria-hidden="true"></i> Download CSV
    <% end %>
  </div>
<% end %>



<div class="panel outer-panel list-view">
  <% @conts&.each do |cont| %>

  <div class="row outer-list-row">
    <div class="col-4">
      <table class="table">
        <tr>
          <td>Name:</td>
          <td><%= cont.full_name %></td>
        </tr>
        <tr>
          <td>Job:</td>
          <td><%= cont.job_title %> | <%= cont.job_desc %> </td>
        </tr>
        <tr>
          <td>E/P:</td>
          <td><%= cont.phone %> | <%= cont.email %></td>
        </tr>

        <tr>
          <td>URL:</td>
          <td><%= cont.web.url %></td>
        </tr>
      </table>
    </div>

    <div class="col-2">
      <table class="table">
        <tr>
          <td>Created:</td>
          <td><%= cont.created_at&.strftime('%x') %></td>
        </tr>
        <tr>
          <td>Verified:</td>
          <td><%= cont.cs_date&.strftime('%x') %></td>
        </tr>
        <tr>
          <td>Email 𝚫:</td>
          <td><%= cont.email_changed&.strftime('%x') %></td>
        </tr>
        <tr>
          <td>Job 𝚫:</td>
          <td><%= cont.job_changed&.strftime('%x') %></td>
        </tr>
      </table>
    </div>

    <div class="col-6">
      <table class="table">

        <% acts = cont.acts %>
        <% acts&.each do |act| %>
          <tr>
            <td><%= act.act_name %>:</td>
            <td><%= act.full_address %></td>
          </tr>
        <% end %>

      </table>
    </div>
  </div>

  <% end %>
</div>

app/views/conts/_conts_list.html.erb
<p id="notice"><%= notice %></p>

<!-- ## ORIGINAL BELOW -->
<div class="panel outer-panel list-view">
  <table class="table table-bordered table-hover table-striped text-nowrap list-view">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Description</th>
      <th>Phone</th>
      <th>email</th>
      <th>Created</th>
      <th>Verified</th>
      <th>Email 𝚫</th>
      <th>Job 𝚫</th>
      <th> <%= icon('fas', 'download', 'CSV') %> </th>
      <th colspan="2">Manage</th>
    </tr>
  </thead>

  <tbody>
    <% conts&.each do |cont| %>
    <% cont_activity = current_user.cont_activities.find_or_create_by(cont_id: cont.id) %>
    <% cont_export = Export.find_by(id: cont_activity.export_id) %>

      <tr>
        <td style="width: 10%;"><%= cont.full_name %></td>
        <td style="width: 10%;"><%= cont.job_title %></td>
        <td style="width: 10%;"><%= cont.job_desc %></td>
        <td style="width: 5%;"><%= cont.phone %></td>
        <td style="width: 10%;"><%= cont.email %></td>
        <td style="width: 5%;"><%= cont.created_at&.strftime('%x') %></td>
        <td style="width: 5%;"><%= cont.cs_date&.strftime('%x') %></td>
        <td style="width: 5%;"><%= cont.email_changed&.strftime('%x') %></td>
        <td style="width: 5%;"><%= cont.job_changed&.strftime('%x') %></td>

        <td style="width: 10%;"><%= "#{cont_export&.export_date&.strftime('%x')} #{cont_export&.file_name}" %></td>

        <td style="width: 5%;"><%= render 'cont_activities/toggle_fav', cont_activity: cont_activity %></td>
        <td style="width: 5%;"><%= render 'cont_activities/toggle_hide', cont_activity: cont_activity %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/conts/_show_cont_web.html.erb
<div class='showWeb' data-id="<%= cont.id %>">
  <!-- #IMPORTANT! CONTACTS RENDERED HERE VIA AJAX. -->
</div>

app/views/conts/download_conts.js.erb
$("#download_conts").html("<%= j (render 'download_conts', conts: @conts) %>");

app/views/conts/index.html.erb
<%= render 'conts', conts: @conts %>

app/views/conts/index.js.erb
$("#yield-content").html("<%= j (render 'conts', conts: @conts) %>");

app/views/conts/new.html.erb
<div class="row">

  <h3>New Cont</h3>

  <div class="row">
    <%= render 'form', cont: @cont %>
  </div>

</div>

<%= link_to 'Back', conts_path %>

app/views/conts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @cont.src %>
</p>

<p>
  <strong>sts:</strong>
  <%= @cont.sts %>
</p>

<p>
  <strong>Act:</strong>
  <%= @cont.act_id %>
</p>

<p>
  <strong>Crm cont num:</strong>
  <%= @cont.crmc %>
</p>

<p>
  <strong>First name:</strong>
  <%= @cont.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @cont.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cont.email %>
</p>

<p>
  <strong>Act:</strong>
  <%= @cont.act %>
</p>

<%= link_to 'Edit', edit_cont_path(@cont) %> |
<%= link_to 'Back', conts_path %>