config/routes.rb
Rails.application.routes.draw do

  resources :users, :only => [:index, :show]
  resources :downloads, only: [:show]
  # resources :activities, only: [:toggle_sts]

  devise_for :users, controllers: { sessions: 'users/sessions' }, path_prefix: 'd', path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'home/index'
  root to: 'home#index'

  resources :acts do
    collection do
      match 'search' => 'acts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'acts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'acts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'acts#hidden', via: [:get, :post], as: :hidden
    end
  end

  resources :conts do
    collection do
      match 'search' => 'conts#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'conts#generate_csv', via: [:get, :post], as: :generate_csv

      match 'followed' => 'conts#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'conts#hidden', via: [:get, :post], as: :hidden

      match 'show_web' => 'conts#show_web', via: [:get, :post], as: :show_web
    end
  end

  resources :webs do
    get :flag_data, on: :collection

    collection do
      match 'search' => 'webs#search', via: [:get, :post], as: :search
      match 'generate_csv' => 'webs#generate_csv', via: [:get, :post], as: :generate_csv
      match 'followed' => 'webs#followed', via: [:get, :post], as: :followed
      match 'hidden' => 'webs#hidden', via: [:get, :post], as: :hidden
      match 'followed_acts' => 'webs#followed_acts', via: [:get, :post], as: :followed_acts
      match 'hidden_acts' => 'webs#hidden_acts', via: [:get, :post], as: :hidden_acts

      match 'show_conts' => 'webs#show_conts', via: [:get, :post], as: :show_conts
    end
  end

  resources :act_activities do
    collection do
      match 'follow_all' => 'act_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'act_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'act_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'act_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'act_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :cont_activities do
    collection do
      match 'follow_all' => 'cont_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'cont_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'cont_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'cont_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'cont_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :web_activities do
    collection do
      match 'follow_all' => 'web_activities#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'web_activities#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'web_activities#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'web_activities#unhide_all', via: [:get, :post], as: :unhide_all
      match 'create_user_activities' => 'web_activities#create_user_activities', via: [:get, :post], as: :create_user_activities
    end
  end

  resources :queries do
    collection do
      match 'follow_all' => 'queries#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'queries#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'queries#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'queries#unhide_all', via: [:get, :post], as: :unhide_all
    end
  end

  resources :tallies, only: [:index] do
    collection do
      match 'follow_all' => 'tallies#follow_all', via: [:get, :post], as: :follow_all
      match 'unfollow_all' => 'tallies#unfollow_all', via: [:get, :post], as: :unfollow_all
      match 'hide_all' => 'tallies#hide_all', via: [:get, :post], as: :hide_all
      match 'unhide_all' => 'tallies#unhide_all', via: [:get, :post], as: :unhide_all
      match 'generate_csv' => 'tallies#generate_csv', via: [:get, :post], as: :generate_csv
      match 'refresh_process' => 'tallies#refresh_process', via: [:get, :post], as: :refresh_process
    end
  end

  # resources :photos, only: [:new, :create, :index, :destroy]
  resources :photos, only: [:new, :create, :index, :destroy] do
    collection do
      match 'perform' => 'photos#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'photos#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :s3s, only: [:new, :create, :index, :destroy]
  resources :s3s, only: [:index, :destroy] do
    collection do
      match 'perform' => 's3s#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 's3s#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  # resources :exports, only: [:new, :create, :index, :destroy]
  resources :exports, only: [:index, :destroy] do
    collection do
      # match 'perform' => 'exports#perform', via: [:get, :post], as: :perform
      match 'download_csv' => 'exports#download_csv', via: [:get, :post], as: :download_csv
    end
  end


  get 'admin/index'
  get 'admin/change_user_level' => 'admin#change_user_level'
  get 'admin/delete_user' => 'admin#delete_user'
  mount DelayedJobWeb => "/delayed_job"

  resources :terms, :links
end

app/models/tally.rb
class Tally < ApplicationRecord

  # serialize :ransack_query, Hash
  # serialize :acts, HashSerializer
  # serialize :links, HashSerializer
  # serialize :act_links, HashSerializer
  # store_accessor :acts, :links, :act_links

  def self.generate_csv_tallies(current_user, tally_hsh)
    TalliesTool.new.delay(priority: 0).generate_csv_tallies(current_user, tally_hsh)
  end


  def self.follow_hide_tallies(action, current_user, tally_hsh)
    if action == 'follow'
      TalliesTool.new.delay(priority: 0).follow_all_tallies(current_user, tally_hsh)
    elsif action == 'unfollow'
      TalliesTool.new.delay(priority: 0).unfollow_all_tallies(current_user, tally_hsh)
    elsif action == 'hide'
      TalliesTool.new.delay(priority: 0).hide_all_tallies(current_user, tally_hsh)
    elsif action == 'unhide'
      TalliesTool.new.delay(priority: 0).unhide_all_tallies(current_user, tally_hsh)
    end
  end

end

app/controllers/tallies_controller.rb
class TalliesController < ApplicationController
  # before_action :set_tally, only: [:show, :edit, :update, :destroy]
  before_action :basic_and_up


  # GET /tallies
  # GET /tallies.json
  def index
    @tallies = Tally.all
  end


  def refresh_process
    Start.delay(priority: 0).get_process_sts
    @process_sts = ProcessStatus.first

    respond_to do |format|
      format.js { render :refresh_process, status: :ok, process_sts: @process_sts }
    end
  end


  def generate_csv
    Tally.generate_csv_tallies(current_user, params[:tally_hsh])
    @tally_hsh = params[:tally_hsh]
    @tally_hsh[:tally_id] = "#{@tally_hsh[:mod_name].downcase}_#{@tally_hsh[:tally_scope]}"

    respond_to do |format|
      format.js { render :update_download_tallies, status: :ok, tally_hsh: @tally_hsh }
    end
    # redirect_to tallies_path
  end


  def follow_all
    flash[:notice] = "Adding Activity Results to Followed List"

    Tally.follow_hide_tallies('follow', current_user, params[:tally_hsh])
    @tally_hsh = params[:tally_hsh]
    @tally_hsh[:tally_id] = "#{@tally_hsh[:mod_name].downcase}_#{@tally_hsh[:tally_scope]}"

    respond_to do |format|
      format.js { render :update_follow_all, status: :ok, tally_hsh: @tally_hsh }
    end
    # redirect_to tallies_path
  end


  def unfollow_all
    flash[:alert] = "Removing Activity Results from Followed List"

    Tally.follow_hide_tallies('unfollow', current_user, params[:tally_hsh])
    @tally_hsh = params[:tally_hsh]
    @tally_hsh[:tally_id] = "#{@tally_hsh[:mod_name].downcase}_#{@tally_hsh[:tally_scope]}"

    respond_to do |format|
      format.js { render :update_unfollow_all, status: :ok, tally_hsh: @tally_hsh }
    end
    # redirect_to tallies_path
  end


  def hide_all
    flash[:notice] = "Adding Activity Results to Hidden List"

    Tally.follow_hide_tallies('hide', current_user, params[:tally_hsh])
    @tally_hsh = params[:tally_hsh]
    @tally_hsh[:tally_id] = "#{@tally_hsh[:mod_name].downcase}_#{@tally_hsh[:tally_scope]}"

    respond_to do |format|
      format.js { render :update_hide_all, status: :ok, tally_hsh: @tally_hsh }
    end
    # redirect_to tallies_path
  end


  def unhide_all
    flash[:alert] = "Removing Activity Results from Hidden List"

    Tally.follow_hide_tallies('unhide', current_user, params[:tally_hsh])
    @tally_hsh = params[:tally_hsh]
    @tally_hsh[:tally_id] = "#{@tally_hsh[:mod_name].downcase}_#{@tally_hsh[:tally_scope]}"

    respond_to do |format|
      format.js { render :update_unhide_all, status: :ok, tally_hsh: @tally_hsh }
    end

    # redirect_to tallies_path
  end



  # GET /tallies/1
  # GET /tallies/1.json
  def show
  end

  # GET /tallies/new
  def new
    # @tally = Tally.new
  end

  # GET /tallies/1/edit
  def edit
  end

  # POST /tallies
  # POST /tallies.json
  def create
    @tally = Tally.new(tally_params)

    respond_to do |format|
      if @tally.save
        format.html { redirect_to @tally, notice: 'Tally was successfully created.' }
        format.json { render :show, status: :created, location: @tally }
      else
        format.html { render :new }
        format.json { render json: @tally.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tallies/1
  # PATCH/PUT /tallies/1.json
  def update
    respond_to do |format|
      if @tally.update(tally_params)
        format.html { redirect_to @tally, notice: 'Tally was successfully updated.' }
        format.json { render :show, status: :ok, location: @tally }
      else
        format.html { render :edit }
        format.json { render json: @tally.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tallies/1
  # DELETE /tallies/1.json
  def destroy
    @tally.destroy
    respond_to do |format|
      format.html { redirect_to tallies_url, notice: 'Tally was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tally
      @tally = Tally.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tally_params
      params.fetch(:tally, {})
    end
end

app/helpers/tallies_helper.rb
module TalliesHelper
#
#   def generate_csv_tallies(params)
#     if params[:mod_name] == 'Act'
#       ActCsvTool.new.start_act_webs_csv_and_log(params, current_user)
#     elsif params[:mod_name] == 'Cont'
#       ContCsvTool.new.start_cont_web_csv_and_log(params, current_user)
#     elsif params[:mod_name] == 'Web'
#       WebCsvTool.new.start_web_acts_csv_and_log(params, current_user)
#     end
#   end
#
#
#   def follow_all_tallies(params)
#     if params[:mod_name] == 'Act'
#       act_ids = Act.send(params[:tally_scope]).pluck(:id)
#       ActActivity.where(user_id: current_user.id, act_id: [act_ids]).update_all(fav_sts: true)
#     elsif params[:mod_name] == 'Cont'
#       cont_ids = Cont.send(params[:tally_scope]).pluck(:id)
#       ContActivity.where(user_id: current_user.id, cont_id: [cont_ids]).update_all(fav_sts: true)
#     elsif params[:mod_name] == 'Web'
#       web_ids = Web.send(params[:tally_scope]).pluck(:id)
#       WebActivity.where(user_id: current_user.id, web_id: [web_ids]).update_all(fav_sts: true)
#     end
#   end
#
#
#   def unfollow_all_tallies(params)
#     if params[:mod_name] == 'Act'
#       act_ids = Act.send(params[:tally_scope]).pluck(:id)
#       ActActivity.where(user_id: current_user.id, act_id: [act_ids]).update_all(fav_sts: false)
#     elsif params[:mod_name] == 'Cont'
#       cont_ids = Cont.send(params[:tally_scope]).pluck(:id)
#       ContActivity.where(user_id: current_user.id, cont_id: [cont_ids]).update_all(fav_sts: false)
#     elsif params[:mod_name] == 'Web'
#       web_ids = Web.send(params[:tally_scope]).pluck(:id)
#       WebActivity.where(user_id: current_user.id, web_id: [web_ids]).update_all(fav_sts: false)
#     end
#   end
#
#
#   def hide_all_tallies(params)
#     if params[:mod_name] == 'Act'
#       act_ids = Act.send(params[:tally_scope]).pluck(:id)
#       ActActivity.where(user_id: current_user.id, act_id: [act_ids]).update_all(hide_sts: true)
#     elsif params[:mod_name] == 'Cont'
#       cont_ids = Cont.send(params[:tally_scope]).pluck(:id)
#       ContActivity.where(user_id: current_user.id, cont_id: [cont_ids]).update_all(hide_sts: true)
#     elsif params[:mod_name] == 'Web'
#       web_ids = Web.send(params[:tally_scope]).pluck(:id)
#       WebActivity.where(user_id: current_user.id, web_id: [web_ids]).update_all(hide_sts: true)
#     end
#   end
#
#
#   def unhide_all_tallies(params)
#     if params[:mod_name] == 'Act'
#       act_ids = Act.send(params[:tally_scope]).pluck(:id)
#       ActActivity.where(user_id: current_user.id, act_id: [act_ids]).update_all(hide_sts: false)
#     elsif params[:mod_name] == 'Cont'
#       cont_ids = Cont.send(params[:tally_scope]).pluck(:id)
#       ContActivity.where(user_id: current_user.id, cont_id: [cont_ids]).update_all(hide_sts: false)
#     elsif params[:mod_name] == 'Web'
#       web_ids = Web.send(params[:tally_scope]).pluck(:id)
#       WebActivity.where(user_id: current_user.id, web_id: [web_ids]).update_all(hide_sts: false)
#     end
#   end
#
end

app/views/tallies/_download_tallies.html.erb
<% @tally_hsh = tally_hsh %>
<div class="downloadTallies" data-id="<% @tally_hsh[:tally_id] %>">

  <td class="text-center">
    <%= link_to generate_csv_tallies_path(tally_hsh: tally_hsh), remote: true, class: 'btn btn-primary btn-md' do %>
      <i class="fa fa-download"></i> Generate CSV
    <% end %>
  </td>

</div>

app/views/tallies/_hide_all.html.erb
<td>
  <% @tally_hsh = tally_hsh %>
  <div class="hideAll" data-id="<% @tally_hsh[:tally_id] %>">

    <%= link_to 'Hide', hide_all_tallies_path(tally_hsh: tally_hsh), remote: true, class: 'btn btn-danger btn-sm' %>

  </div>
</td>

app/views/tallies/_mo_1_2.html.erb
<br>
<h5 class='text-center'>Activity Report</h5>
<h6 class="text-center"><%= icon('fas', 'calendar-alt', 'Last Month') %> </h6>

<!-- ACTS SCOPES BEGIN -->
<h6 class=""><%= icon('fas', 'building', 'Accounts') %> </h6>

<div class="row">
  <div class="col-md-12">
    <table class="table">

      <!-- thead rendered as partial -->
      <%= render 'tallies/tally_thead' %>

      <tbody>
        <!-- ACTS SCOPES BEGIN -->
        <!-- Act created_at -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'Created', mod_name: 'Act', tally_scope: 'created_between_mo_1_2'} %>

        <!-- Act adr_changed -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'Address Changed', mod_name: 'Act', tally_scope: 'adr_changed_between_mo_1_2'} %>

        <!-- Act act_changed -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'Profile Changed', mod_name: 'Act', tally_scope: 'act_changed_between_mo_1_2'} %>

        <!-- Act ax_date -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'InActive', mod_name: 'Act', tally_scope: 'ax_date_between_mo_1_2'} %>
      </tbody>
    </table>
  </div>
</div>

<br>

<!-- CONTS SCOPES BEGIN -->
<h6 class=""><%= icon('fas', 'users', 'Contacts') %> </h6>

<div class="row">
  <div class="col-md-12">
    <table class="table">

      <!-- thead rendered as partial -->
      <%= render 'tallies/tally_thead' %>

    <tbody>
      <!-- Cont created_at -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Created', mod_name: 'Cont', tally_scope: 'created_between_mo_1_2'} %>

      <!-- Cont job_changed -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Job Changed', mod_name: 'Cont', tally_scope: 'job_changed_between_mo_1_2'} %>

      <!-- Cont cont_changed -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Profile Changed', mod_name: 'Cont', tally_scope: 'cont_changed_between_mo_1_2'} %>

      <!-- Cont email_changed -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Email Changed', mod_name: 'Cont', tally_scope: 'email_changed_between_mo_1_2'} %>

      <!-- Cont cx_date -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'InActive', mod_name: 'Cont', tally_scope: 'cx_between_mo_1_2'} %>
    </tbody>
  </table>
  </div>
</div>

<br>

<!-- WEBS SCOPES BEGIN -->
<h6 class=""><%= icon('fas', 'external-link-alt', 'Websites') %> </h6>

<div class="row">
  <div class="col-md-12">
    <table class="table">

      <!-- thead rendered as partial -->
      <%= render 'tallies/tally_thead' %>

      <tbody>
        <!-- Web created_at -->
        <%= render 'tallies/tally_webs', tally_hsh: {th: 'Created', mod_name: 'Web', tally_scope: 'created_between_mo_1_2'} %>

        <!-- Web web_changed -->
        <%= render 'tallies/tally_webs', tally_hsh: {th: 'Changed', mod_name: 'Web', tally_scope: 'web_changed_between_mo_1_2'} %>

        <!-- Web wx_date -->
        <%= render 'tallies/tally_webs', tally_hsh: {th: 'InActive', mod_name: 'Web', tally_scope: 'wx_date_between_mo_1_2'} %>

      </tbody>
    </table>
  </div>
</div>

app/views/tallies/_process_sts.html.erb
<div id="refreshProcess">


  <div class="panel">
    <div class="row">
      <div class="col-md-12">
        <h5 class="section-header text-center">Process Status

          <span style="font-size: 14px;" class="font-italic text-primary"> From <%= time_ago_in_words(process_sts.updated_at) %> Ago </span>

          <span>
            <%= link_to refresh_process_tallies_path, remote: true, class: 'btn btn-default btn-refresh' do %>
            <%= icon('fas', 'sync', 'Refresh') %>
            <% end %>
          </span>

        </h5>

      </div>
    </div>
  </div>



  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th class="text-center">Category</th>
          <th class="text-center">URL Mine</th>
          <th class="text-center">Template Mine</th>
          <th class="text-center">Staff Page Mine</th>
          <th class="text-center">Google Mine</th>
          <th class="text-center">Brand Mine</th>
          <th class="text-center">Staff Mine</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td class="text-center">Total</td>
          <td class="text-center"><%= number_with_delimiter(process_sts.url_total, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.temp_total, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.page_total, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.gp_total, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.brand_total, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.cont_total, :delimiter => ',') %></td>
        </tr>

        <tr>
          <td class="text-center">Queued</td>
          <td class="text-center"><%= number_with_delimiter(process_sts.ver_url, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.find_temp, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.find_page, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.gp, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.find_brand, :delimiter => ',') %></td>
          <td class="text-center"><%= number_with_delimiter(process_sts.cont_scraper, :delimiter => ',') %></td>
        </tr>
      </tbody>

    </table>
  </div>




</div>

app/views/tallies/_process_sts_wrap.html.erb
<% process_sts = ProcessStatus.first %>
<%= render 'tallies/process_sts', process_sts: process_sts %>

app/views/tallies/_unfollow_all.html.erb
<%= link_to 'Reset', unfollow_all_tallies_path(tally_hsh: tally_hsh), remote: true, class: 'btn btn-default btn-sm' %>

app/views/tallies/_unfollow_all_wrap.html.erb
<td>
  <% @tally_hsh = tally_hsh %>
  <div class="unfollowAll" data-id="<% @tally_hsh[:tally_id] %>">
    <%= render 'tallies/unfollow_all', tally_hsh: @tally_hsh %>
  </div>
</td>

app/views/tallies/_unhide_all.html.erb
<%= link_to 'Reset', unhide_all_tallies_path(tally_hsh: tally_hsh), remote: true, class: 'btn btn-default btn-sm' %>

app/views/tallies/_wk_1_2.html.erb
<br>
<h5 class='text-center'>Activity Report</h5>
<h6 class="text-center"><%= icon('fas', 'calendar-alt', 'Last Week') %> </h6>

<!-- ACTS SCOPES BEGIN -->
<h6 class=""><%= icon('fas', 'building', 'Accounts') %> </h6>

<div class="row">
  <div class="col-md-12">
    <table class="table">

      <!-- thead rendered as partial -->
      <%= render 'tallies/tally_thead' %>

      <tbody>
        <!-- ACTS SCOPES BEGIN -->
        <!-- Act created_at -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'Created', mod_name: 'Act', tally_scope: 'created_between_wk_1_2'} %>

        <!-- Act adr_changed -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'Address Changed', mod_name: 'Act', tally_scope: 'adr_changed_between_wk_1_2'} %>

        <!-- Act act_changed -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'Profile Changed', mod_name: 'Act', tally_scope: 'act_changed_between_wk_1_2'} %>

        <!-- Act ax_date -->
        <%= render 'tallies/tally_acts', tally_hsh: {th: 'InActive', mod_name: 'Act', tally_scope: 'ax_date_between_wk_1_2'} %>
      </tbody>
    </table>
  </div>
</div>

<br>

<!-- CONTS SCOPES BEGIN -->
<h6 class=""><%= icon('fas', 'users', 'Contacts') %> </h6>

<div class="row">
  <div class="col-md-12">
    <table class="table">

      <!-- thead rendered as partial -->
      <%= render 'tallies/tally_thead' %>

    <tbody>
      <!-- Cont created_at -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Created', mod_name: 'Cont', tally_scope: 'created_between_wk_1_2'} %>

      <!-- Cont job_changed -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Job Changed', mod_name: 'Cont', tally_scope: 'job_changed_between_wk_1_2'} %>

      <!-- Cont cont_changed -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Profile Changed', mod_name: 'Cont', tally_scope: 'cont_changed_between_wk_1_2'} %>

      <!-- Cont email_changed -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'Email Changed', mod_name: 'Cont', tally_scope: 'email_changed_between_wk_1_2'} %>

      <!-- Cont cx_date -->
      <%= render 'tallies/tally_conts', tally_hsh: {th: 'InActive', mod_name: 'Cont', tally_scope: 'cx_between_wk_1_2'} %>
    </tbody>
  </table>
  </div>
</div>

<br>

<!-- WEBS SCOPES BEGIN -->
<h6 class=""><%= icon('fas', 'external-link-alt', 'Websites') %> </h6>

<div class="row">
  <div class="col-md-12">
    <table class="table">

      <!-- thead rendered as partial -->
      <%= render 'tallies/tally_thead' %>

      <tbody>
        <!-- Web created_at -->
        <%= render 'tallies/tally_webs', tally_hsh: {th: 'Created', mod_name: 'Web', tally_scope: 'created_between_wk_1_2'} %>

        <!-- Web web_changed -->
        <%= render 'tallies/tally_webs', tally_hsh: {th: 'Changed', mod_name: 'Web', tally_scope: 'web_changed_between_wk_1_2'} %>

        <!-- Web wx_date -->
        <%= render 'tallies/tally_webs', tally_hsh: {th: 'InActive', mod_name: 'Web', tally_scope: 'wx_date_between_wk_1_2'} %>
      </tbody>
    </table>
  </div>
</div>

app/views/tallies/update_follow_all.js.erb
var followAllDiv = $('div.followAll[data-id="<%= @tally_hsh[:tally_id] %>"]');
followAllDiv.html("<%= j (render 'follow_all', tally_hsh: @tally_hsh) %>");

app/views/tallies/update_hide_all.js.erb
var hideAllDiv = $('div.hideAll[data-id="<%= @tally_hsh[:tally_id] %>"]');
hideAllDiv.html("<%= j (render 'hide_all', tally_hsh: @tally_hsh) %>");

app/views/tallies/update_unfollow_all.js.erb
var unfollowAllDiv = $('div.unfollowAll[data-id="<%= @tally_hsh[:tally_id] %>"]');
unfollowAllDiv.html("<%= j (render 'unfollow_all', tally_hsh: @tally_hsh) %>");